server:
  port: 9000

spring:
  datasource:
#    url: jdbc:mysql://114.116.233.109:3306/vehicle_condition?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
    url: jdbc:mysql://127.0.0.1:3306/vehicle_condition_dev?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver